- lua/lazygit.lua
As it is, when trying to call lazygit with a file that contains a space char in its path will fail, as the path will be broken into two arguments when passed to lazygit. The quotes I added fixes that. Then, there is the fact that the path returned by git has a newline at the end, so I trim the path to remove newlines at the beginning and end of paths. This version works with projects I have inside "Google Drive".
I DID NOT TEST THIS, but are basically the same changes I made on the other branch.
> Fixes paths with spaces

- README.md
- lua/lazygit.lua
- plugin/lazygit.vim
This PR fixes the issue  #23 
The default popup window corners are round and may not look so good with some font. This PR adds the option g.lazygit_floating_window_corner_chars to allow user to customize the corner characters.
> Add option to customize popup window corners

- lua/lazygit.lua
Setting `-p <path>` is the same as setting `-w <path> -g <path>/.git/`,
but this eliminates the possibility that the git dir could be outside of
the work tree, or else named something besides `.git`. Use case for me
is my configuration files are VC'ed in a git repo, and checked out into
`$HOME` (the work tree). The repo is a bare repo elsewhere.
> Don't use -p if GIT_DIR or GIT_WORK_TREE are set

- lua/lazygit.lua
When calling `:LazyGit` when editing a file in a directory that has spaces in
the path name, the call to lazygit would fail. Simple fix.
> fnameescape path before calling lazygit

- README.md
- lua/lazygit.lua
Lots of plugins have the same basic code to open floating windows. I'd love it
if there were a standard API for this, but the closest thing I have found is
[plenary.nvim](https://github.com/nvim-lua/plenary.nvim), which is already a
required dependency of a number of popular plugins (e.g.
[Telescope](https://github.com/nvim-lua/telescope.nvim)). Using plenary to
manage floating windows allow for a consistent UI across multiple plugins, for
example, using `winblend` for transparency.
This patch adds a configuration variable
`g:lazygit_floating_window_use_plenary`, which, if set, checks for and uses
plenary.window.float to open lazygit's floating window. Default and fallback
behavior is unchanged.
After review, if you'd like to make this the default, I wouldn't complain :)
> Add option to use plenary.nvim to manage floating window

- lua/lazygit.lua
I use this plugin on Windows and it recently broke. I noticed it was attempting to launch lazygit using bash. Looking at the code, it seems that a change went in to enforce usage of 'bash' as the Shell. This broke functionality on Windows. This PR fixes this bug with a simple check for Win32 and not changing the shell if that's the case.
> fix lazygit launching on Windows

- lua/lazygit.lua
when execute `git rev-parse --show-superproject-working-tree` in a non git repository directory.
It will error: `fatal: not a git repository (or any of the parent directories): .git`
and 
'lazygit -p "a not exist path"` will meet: `*fsPathError stat /xxxxxx/.git/: no such file or directory` from lazygit.
> Fix git rev path check when execute not in a git repo

- ftplugin/gitcommit.vim
- lua/lazygit.lua
I love the nvr implementation with LazyGit and this plugin to write my commit messages from within Neovim without spawning a new instance. But one thing that has bugged me all the time is that whenever I leave the "commit message window" to check for words, information or whatever it tries to reopen the LazyGit window (which sometimes did not work and left me with an open and empty floating window) and I have to close it again manuallly
I saw in #12 that you got a "cannot delete buffer" error when trying to use a different autocommand event for it
After playing around with it myself and reading some documentation I (think I) found the root cause for this and a working solution:
When we close the git commit message buffer the `BufUnload` autocommand is triggered and the `LazyGit` command …
> fix: improve git commit message via nvr

- lua/lazygit.lua
this change fixes for me both issues @kdheepak 
* Submodule > lazyg opens for parent repo #47
* Not working with git worktrees #46
> fix repo recognition & add telescope support

- lua/lazygit.lua
This command will check for any changed buffers and refresh them, useful when we switch branches, stash or discard changes ( #53 )
> add vim checktime cmd to refresh buffers on lazygit exit

- lua/lazygit.lua
Lets say you have multiple windows/splits on your current tabpage
```text
┌-------------------------------------------┐
│                  │                        │
│                  │            B           │
│                  │                        │
│        A         │------------------------│
│                  │                        │
│                  │            C           │
│                  │                        │
└-------------------------------------------┘
``` 
If your cursor is in window B when you open LazyGit, after you close the floating window the cursor will be placed in the *first* window of the tabpage, which here would be window A. To mitigate this I just save the current window when opening lazygit and restoring it on exit.
Not sure if this should be …
> feat: return to the previous window on exit

- README.md
- lua/lazygit.lua
- lua/lazygit/utils.lua
- plugin/lazygit.vim
Further to the discussion in #75, this adds a command called `LazyGitCurrentFile` that opens `lazygit` in a floating terminal at the project root of the buffer under the cursor.
This required parametrizing the `lazygit.nvim/utils.lua:get_root` function to accept a path argument.
> Add LazyGitCurrentFile command

- lua/lazygit.lua
> fix(lazygit.lua): escape 'space' in filepath

- lua/lazygit.lua
Fixed a minor bug that caused :LazyGitFilter to not correctly close the floating terminal.
> fix: store win and buffer for :LazyGitFilter command

- README.md
Lists in lua are specified with curly brackets, not square brackets.
> docs: Fix lua example

- lua/lazygit/window.lua
When using `vim.g.lazygit_floating_window_use_plenary = 1`,
Nothing is returned by `plenary.percentage_range_window` from **open_floating_window**, and `win`/`buffer` variables are `nil`.
As result LazyGit buffer is not closed in **lazygit.on_exit** callback due to an exception from `vim.api.nvim_win_close(win, true)`: _ua/lazygit.lua:28: Expected Lua number_
In addition, after LazyGit exit, the window is still opened with the text: `[Process exited 0]`
This PR fixes the issue by returning `ret.win_id, ret.bufnr` from **open_floating_window** when _plenary_ is used.
> fix: plenary.percentage_range_window returns 'win_id' and 'bufnr'

- lua/lazygit/window.lua
The function **open_floating_window** returns `win, border_window`, what is incorrect.
As result, in callback **on_exit**, `vim.api.nvim_buf_is_valid(buffer)` is `false`, and LazyGit terminal buffer persists as orphan (and hidden) with text `[Process exited 0]`.
Every time LazyGit exits, an orphan terminal buffer remains , which can be checked, e.g. in Neo-tree:
```
term://~/.config/nvim//4010044:lazygit #3
term://~/.config/nvim//4010053:lazygit #7
...
```
This PR provides a fix to return `LAZYGIT_BUFFER` instead of `border_window`, so that the behavior is correct with no issues on my side.
In fact, it is not clear for me, why `LAZYGIT_BUFFER` is present, it is always set to `nil` in **on_exit** callback, probably some refactoring is required to remove `LAZYGIT_BUFFER` and …
> fix: open_floating_window should return lazygit buffer instead of border_window

- lua/lazygit/utils.lua
This change fixes the issue where vim starts using bash (in newly opened `:terminal` instances) instead of zsh after using `:LazyGitCurrentFile`.
Steps to reproduce issue:
1. Open `nvim` from a directory that is not part of any git repository.
2. Set vim.o.buffer to a shell that is not bash (you will not need to do this if you already don't use bash).
3. Call `:terminal` to make sure that neovim is opening the selected non-bash shell.
4. Call `:LazyGitCurrentFile` and the close out of the resulting pop-up instance of lazygit.
5. Call `:terminal` again. You should see the problem where now neovim is opening a bash instance. You can print `vim.o.shell` to see that it is bash.
After you include my change, this issue is fixed and the neovim will properly open the selected shell in step 5.
> fix: Cover missing edge case in resetting user's preferred shell

- README.md
- lua/lazygit.lua
- lua/lazygit/utils.lua
Hey @kdheepak , Thanks for creating this plugin! It's been major part of my daily workflow for over a year now.
Lazygit supports using multiple config files: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md?plain=1#L346
This PR adds code to parse vim.g.lazygit_config_file_path as a `string | table`.
PS: I'm a total noob at lua, so please let me know if anything can be done better!
> feat: Add support for multiple lazygit config files

- lua/lazygit/window.lua
There is an existing user config for setting the winblend value of the lazygit floating window. This controls the background transparency of the window. However, this config option is not respected if the lazygit window is created using plenary (another user config). This change forces the plenary window to use the existing config for transparency.
> feat: Use winblend config for plenary window

- plugin/lazygit.vim
Was trying to get this plugin working with my nixvim configuration and kept wondering why I couldn't get the plugin to recognize that I'd set the custom config file settings. Eventually realized it was because the plugin was loading after my init.lua and overriding what I'd set back to the defaults. This change makes it so that the defaults are only set if the variables haven't been set already, like the rest of the config variables.
> fix: only set custom config file settings if not set already

- README.md
When using lazy.nvim, the Plugin should only load now, if one of its functions is called.
> Updated install lazy.nvim section in README.md

- README.md
Add a recommendation to use 'keys' to set the keybinding to load lazygit.nvim if using lazy.nvim. If the keybinding is set elsewhere, e.g. in a config() function, the plugin won't be loaded the first time this is run - the user will have to use `: LazyGit` first.
> Update example lazy.nvim config in README

- lua/lazygit.lua
:LazyGitFilterCurrentFile currently breaks if the path of the file contains a space. Fixed by wrapping the path in quotes.
> fix: use quotes to allow filtering on files with spaces in path

- README.md
This is a probable fix for issue #128. 
~ Thanks
> Lazy install code fix

- lua/lazygit.lua
Be able to pass `work-tree` and `git-dir` arguments for Lazygit.
This would be very useful when using a bare git repo, so that Lazygit could still be used to manage the repo.
> feat: use git-dir and work-tree from environment

- README.md
- lua/lazygit.lua
If I close LazyGit after having done some changes (Commit something/change branch…) I often run into some minor inconsistency with the UI on screen, that does not get updated to reflect the changes.
In particular the issue I’m having is with the color of the files inside the [neo-tree](https://github.com/nvim-neo-tree/neo-tree.nvim) view. I understand this is a really insignificant issue, but I still would like to fix it.
I have added an option that allow an user of the plugin to add a callback that is automatically executed after exiting LazyGit, so that I can put there the necessary code to refresh my UI
> feat: Add option for user's on exit callback

- lua/lazygit.lua
We have already worked out the "git root" for the current buffer, we did this to work out the relative path. We might as well use this information when calling `lazygitfilter`.
This now allows `lazygitfiltercurrentfile` to work, whether your actual cwd is a git repository ('normal' workflow) or a project folder containing many repositories (another workflow many vim users follow).
It looks like LSP did an autoformat on the file also, I can revert those two lines if required.
> feat: Allow current buffer commits to show on the already worked out Git root

- lua/lazygit/window.lua
signcolumns hide the left borders(for configs that have the signcolumn opt active. Requires to be set twice(this may be a personal config scenario). The first sets for the floating window created, the second for lazygit's UI.
> fix: signcolumn overlaps left borders

- lua/lazygit.lua
Currently, at least `:LazyGitCurrentFile` doesn't handle paths with spaces correctly as they aren't escaped (if your current path is a valid shell script, this can also lead to code execution)
This PR changes the lazygit commands from strings to lists to avoid this problem
> Fix command injection and errors when repo name contains spaces

- lua/lazygit/window.lua
Fixes #116 
https://github.com/kdheepak/lazygit.nvim/assets/167217/729c203a-c873-45c8-8346-cd7266d9eb2f
The `defer` is a bit of a hack, but otherwise the new size doesn't get enough time to be properly registered. It still sometimes messes up and positions itself slightly off sometimes if I try to do it several times fast, so maybe the delay needs to be adjusted, some debounce added, or we might want to find a different method for ensuring the window has the correct size.
> feat: resize window on nvim resize

- lua/lazygit/window.lua
Fixes bug created in the [commit ac4a400](https://github.com/kdheepak/lazygit.nvim/commit/ac4a400b256a63ae9d533b022db9b98d3358ef55)
**Prevent crash when using plenary.window.float for floating window**
This MR fixes a bug caused by inconsistent return values from get_window_pos() when vim.g.lazygit_floating_window_use_plenary is enabled.
**Problem**
When plenary.window.float is used, get_window_pos() returned (win_id, bufnr) instead of the expected (width, height, row, col). This led to a runtime error:
E5108: Error executing lua ...window.lua:33: attempt to perform arithmetic on local 'row' (a nil value)
**Solution**
Ensure that get_window_pos() always returns consistent values and explicitly handle the Plenary case in open_floating_window().
This prevents arithmetic operations on nil …
> fix: plenary usage crash

- lua/lazygit.lua
since `open_floating_window` use async way `vim.defer_fn` to create window, `lazygit` executed with a sync way of `vim.fn.jobstart` in `exec_lazygit_command`, it can't get the floating window size at the banging
before:
https://github.com/user-attachments/assets/771b4099-c398-42b4-a80f-367f2d1305e7
after:
https://github.com/user-attachments/assets/12cb7381-625c-49c3-bf61-0e385ce79c76
> fix(window): set correct window size for lazygit to render
